name: Flask CI
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Matches your EC2 setup (python3.12)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          # Placeholder for unit tests
          # Replace with your test command, e.g., python -m unittest discover
          echo "No tests defined yet. Add unit tests to your project."
      - name: Finish
        run: echo "CI pipeline completed successfully!"
